[[main]]
name = "Investigations"
url = "/investigations/"
weight = 1

[[main]]
name = "Events"
url = "/topics/events/"
weight = 4

[[main]]
name = "Newsletters"
url = "/newsletters/"
weight = 3

[[main]]
name = "State College"
url = "/statecollege/"
weight = 2

[[main_about]]
name = "About"
url = "/about/"
weight = 1

[[main_about]]
name = "Mission"
parent = "About"
url = "/about/mission/"
weight = 1

[[main_about]]
name = "Meet the Team"
parent = "About"
url = "/about/staff/"
weight = 1

[[main_about]]
name = "Our Partners"
parent = "About"
url = "/about/partners"
weight = 1

[[main_about]]
name = "Careers"
parent = "About"
url = "/about/jobs/"
weight = 1

[[main_about]]
name = "Contact"
parent = "About"
url = "/contact/"
weight = 1

[[main_support]]
name = "Support Spotlight PA"
url = "/support/"
weight = 2

[[main_support]]
name = "Ways to give"
parent = "Support Spotlight PA"
url = "/support/"
weight = 1

[[main_support]]
name = "How we're funded"
parent = "Support Spotlight PA"
url = "/support/funders-and-members"
weight = 2

[[main_more]]
name = "News"
url = "/news/"
weight = 3

[[main_more]]
parent = "News"
name = "Criminal Justice"
url = "/topics/criminal-justice/"
weight = 1

[[main_more]]
parent = "News"
name = "Economy"
url = "/topics/economy/"
weight = 1

[[main_more]]
parent = "News"
name = "Elections"
url = "/elections/"
weight = 1

[[main_more]]
parent = "News"
name = "State Capitol"
url = "/topics/the-capitol/"
weight = 1

[[main_more]]
parent = "News"
name = "Health"
url = "/topics/health/"
weight = 1

[[main_more]]
parent = "News"
name = "How Harrisburg Works"
url = "/topics/how-harrisburg-works/"
weight = 1

[[main_more]]
parent = "News"
name = "Local Government"
url = "/topics/local-government/"
weight = 1

[[main_more]]
parent = "News"
name = "Penn State"
url = "/topics/penn-state/"
weight = 1

[[main_more]]
parent = "News"
name = "Rural Issues"
url = "/topics/rural-issues/"
weight = 1

[[main_more]]
parent = "News"
name = "More Topics"
url = "/topics/"
weight = 10


[[main_more]]
parent = "News"
name = "Archives"
url = "/news/"
weight = 1

[[about]]
name = "Our Mission"
url = "/about/mission/"
weight = 2

[[about]]
name = "Meet the Team"
url = "/about/staff/"
weight = 3

[[about]]
name = "Spotlight PA Partners"
url = "/about/partners"
weight = 4

[[about]]
name = "Careers"
url = "/jobs/"
weight = 5

[[about]]
name = "Contact"
url = "/contact/"
weight = 6

[[news]]
name = "Investigations"
url = "/investigations/"
weight = 7

[[news]]
name = "The Capitol"
url = "/topics/the-capitol/"
weight = 8

[[news]]
name = "More Topics"
url = "/topics/"
weight = 9

[[news]]
name = "State College Region"
url = "/statecollege/"
weight = 10

[[news]]
name = "Events"
url = "/events/"
weight = 11

[[news]]
name = "Archives"
url = "/news/"
weight = 12

[[newsletters]]
name = "PA Post"
url = "/newsletters/papost/"
weight = 3

[[newsletters]]
name = "The Investigator"
url = "/newsletters/investigator/"
weight = 4

[[newsletters]]
name = "PA Local"
url = "/newsletters/palocal/"
weight = 5

[[newsletters]]
name = "Penn State Alerts"
url = "/newsletters/pennstatealert/"
weight = 6

[[newsletters]]
name = "Talk of the Town"
url = "/newsletters/talkofthetown/"
weight = 7

[[support]]
name = "Ways to Give"
url = "/support/"
weight = 1

[[support]]
name = "How We're Funded"
url = "/support/funders-and-members#major-donors-and-funders-since-launch"
weight = 2

[[social]]
name = "Social"
url = "#"
weight = 1

[[social]]
name = "News Apps"
url = "#"
weight = 20

[[social]]
name = "Tools"
url = "#"
weight = 30

[[social]]
name = "Facebook"
url = "https://www.facebook.com/SpotlightPennsylvania"
weight = 1
Parent = "Social"

[social.params]
icon = "fb"

[[social]]
name = "Twitter"
url = "https://www.twitter.com/SpotlightPA"
weight = 2
Parent = "Social"

[social.params]
icon = "twitter"

[[social]]
name = "Instagram"
url = "https://www.instagram.com/Spotlightpennsylvania/"
weight = 3
Parent = "Social"

[social.params]
icon = "ig"

[[social]]
name = "Apple News"
url = "https://apple.news/TJOxac5Y3SDWgviiNxcD9gA"
weight = 4
Parent = "News Apps"

[social.params]
icon = "apple"

[[social]]
name = "RSS"
url = "/feeds/full.xml"
weight = 7
Parent = "News Apps"

[social.params]
icon = "rss"

[[social]]
name = "Flipboard"
url = "https://flipboard.com/@SpotlightPA"
weight = 6
Parent = "News Apps"

[social.params]
icon = "flip"

[[social]]
name = "Github"
url = "https://www.github.com/spotlightpa/"
weight = 9
Parent = "Tools"

[social.params]
icon = "gh"

[[social]]
name = "Google News"
url = "https://news.google.com/publications/CAAqBwgKMJOpkgswx-CnAw"
weight = 5
Parent = "News Apps"

[social.params]
icon = "google"
