[[main]]
name = "Our Mission"
pre = "is-uppercase"
url = "/about/"
weight = 1

[[main]]
name = "Our Team"
pre = "is-uppercase"
url = "/about/staff/"
weight = 2

[[main]]
name = "Supporters"
pre = "is-uppercase"
url = "/support/"
weight = 3

[[main]]
name = "FAQ"
pre = "is-uppercase"
url = "/about/faq/"
weight = 4

[[main]]
name = "Become a partner"
pre = "is-uppercase"
url = "/contact/"
weight = 5

[[main]]
name = "Send a tip"
pre = "is-uppercase has-text-warning"
url = "/tips/"
weight = 6

[[footer]]
name = "Home"
pre = "is-uppercase"
url = "/"
weight = 1

[[footer]]
name = "Supporters"
pre = "is-uppercase"
url = "/support/"
weight = 2

[[footer]]
name = "Contact"
pre = "is-uppercase"
url = "/contact/"
weight = 3

[[footer]]
name = "Tips"
pre = "is-uppercase"
url = "/tips/"
weight = 4

[[footer]]
name = "Press releases"
pre = "is-uppercase"
url = "/press-releases/"
weight = 5

[[about]]
name = "About"
pre = "is-uppercase"
url = "/about/"
weight = 1

[[about]]
name = "Staff"
pre = "is-uppercase"
url = "/about/staff/"
weight = 2

[[about]]
name = "Diversity"
pre = "is-uppercase"
url = "/about/diversity/"
weight = 3

[[about]]
name = "FAQ"
pre = ""
url = "/about/faq/"
weight = 4

[[social]]
name = "Facebook"
pre = "is-uppercase"
url = "https://www.facebook.com/SpotlightPennsylvania"
weight = 1

[[social]]
name = "Twitter"
pre = "is-uppercase"
url = "https://www.twitter.com/SpotlightPA"
weight = 2

[[social]]
name = "Github"
pre = "is-uppercase"
url = "https://www.github.com/spotlightpa/"
weight = 3
