[[main]]
name = "Our Mission"
pre = "is-uppercase"
url = "/about/mission/"
weight = 1

[[main]]
name = "Our Team"
pre = "is-uppercase"
url = "/about/staff/"
weight = 2

[[main]]
name = "Newsletters"
pre = "is-uppercase"
url = "/newsletters/"
weight = 3

[[main]]
name = "FAQ"
pre = "is-uppercase"
url = "/about/faq/"
weight = 4

[[main]]
name = "Send a tip"
pre = "is-uppercase"
url = "/tips/"
weight = 5

[[footer]]
name = "Home"
pre = "is-uppercase"
url = "/"
weight = 1

[[footer]]
name = "Supporters"
pre = "is-uppercase"
url = "/support/"
weight = 2

[[footer]]
name = "Contact"
pre = "is-uppercase"
url = "/contact/"
weight = 3

[[footer]]
name = "Tips"
pre = "is-uppercase"
url = "/tips/"
weight = 4

[[footer]]
name = "Press releases"
pre = "is-uppercase"
url = "/press-releases/"
weight = 5

[[footer]]
name = "Newsletters"
pre = "is-uppercase"
url = "/newsletters/"
weight = 6

[[footer]]
name = "News Archive"
pre = "is-uppercase"
url = "/news/"
weight = 7

[[footer]]
name = "Search"
pre = "is-uppercase"
post = "x-data=\"{}\" @click.prevent=\"$dispatch('modal:search:open')\""
url = "/search/"
weight = 8

[[footer]]
name = "Special Projects & Investigations"
pre = "is-uppercase"
url = "/series/"
weight = 9

[[footer]]
name = "Topic Archive"
pre = "is-uppercase"
url = "/topics/"
weight = 10

[[footer]]
name = "Events"
pre = "is-uppercase"
url = "/events/"
weight = 11

[[footer]]
name = "Donate"
pre = "is-uppercase"
url = "/donate/"
weight = 12

[[about]]
name = "About Us"
pre = "is-uppercase"
url = "/about/"
weight = 1

[[about]]
name = "Our Mission"
pre = "is-uppercase"
url = "/about/mission/"
weight = 2

[[about]]
name = "Partners"
pre = "is-uppercase"
url = "/about/partners/"
weight = 3

[[about]]
name = "Staff"
pre = "is-uppercase"
url = "/about/staff/"
weight = 4

[[about]]
name = "Diversity"
pre = "is-uppercase"
url = "/about/diversity/"
weight = 5

[[about]]
name = "FAQ"
pre = "is-uppercase"
url = "/about/faq/"
weight = 6

[[about]]
name = "Jobs"
pre = "is-uppercase"
url = "/about/jobs/"
weight = 7

[[social]]
name = "Facebook"
pre = "is-uppercase"
url = "https://www.facebook.com/SpotlightPennsylvania"
weight = 1

[[social]]
name = "Twitter"
pre = "is-uppercase"
url = "https://www.twitter.com/SpotlightPA"
weight = 2

[[social]]
name = "Instagram"
pre = "is-uppercase"
url = "https://www.instagram.com/Spotlightpennsylvania/"
weight = 3

[[social]]
name = "Apple News"
pre = "is-uppercase"
url = "https://apple.news/TJOxac5Y3SDWgviiNxcD9gA"
weight = 4

[[social]]
name = "Crowdcast"
pre = "is-uppercase"
url = "/events/"
weight = 5

[[social]]
name = "Flipboard"
pre = "is-uppercase"
url = "https://flipboard.com/@SpotlightPA"
weight = 6

[[social]]
name = "Github"
pre = "is-uppercase"
url = "https://www.github.com/spotlightpa/"
weight = 7

[[social]]
name = "Google News"
pre = "is-uppercase"
url = "https://news.google.com/publications/CAAqBwgKMJOpkgswx-CnAw"
weight = 8
