banner-active = true
banner = "**RSVP NOW: Our panel of experts answer your questions on the COVID-19 resurgence Â»**"
banner-link = "https://inquirer.zoom.us/webinar/register/WN_s2yh3_s8TOqQ3J8UkgqGew"
banner-bg-color = "#c200ff"
banner-text-color = "#ffffff"
promo-active = true
promo-type = "image"
promo-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01ga/518v/banner-12.png, https://files.data.spotlightpa.org/uploads/01ga/518w/banner-9.png, https://files.data.spotlightpa.org/uploads/01ga/518w/banner-7.png, https://files.data.spotlightpa.org/uploads/01ga/518w/banner-5.png"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01ga/51mm/rectangle-2.png, https://files.data.spotlightpa.org/uploads/01ga/51mm/rectangle-3.png, https://files.data.spotlightpa.org/uploads/01ga/51mm/rectangle-1.png"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
show-newsletter = true
show-sticky = true
sticky-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
sticky-image = "https://files.data.spotlightpa.org/uploads/01ga/51qc/square-8.png, https://files.data.spotlightpa.org/uploads/01ga/51qc/square-7.png, https://files.data.spotlightpa.org/uploads/01ga/51qc/square-6.png, https://files.data.spotlightpa.org/uploads/01ga/51qd/square-5.png"
sticky-link = "/donate/"