banner = "**Latest update: Spotlight PA opens new newsroom in Harrisburg with seven full-time investigative reporters**"
banner-link = "https://www.spotlightpa.org/press-releases/"
banner-active = true