promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
promo-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
banner = "We’re raising $10,000 from today through Thursday to help power our reporting on the state government, and all donations will be DOUBLED. **Here's how to help »**"
banner-link = "/news/2020/05/pennsylvania-local-news-spotlight-pa-donation/"
banner-active = false