promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
promo-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
banner = "**SUPPORT SPOTLIGHT PA:** We need hard-hitting accountability journalism in Pennsylvania now more than ever."
banner-link = "/donate/"
banner-active = true
